"""Markdown report generation."""

from __future__ import annotations

from aesop.domain.findings import AnalysisResult, Finding
from aesop.reports.sections import (
    architecture_summary,
    severity_badge,
    sort_findings_by_severity,
)


def render_markdown(result: AnalysisResult) -> str:
    """Generate a complete Markdown threat model report."""
    sections = [
        _title(result),
        _system_summary(result),
        _severity_summary(result),
        _findings_table(result),
        _detailed_findings(result),
        _atlas_section(result),
        _mitigations_summary(result),
        _diagram_section(result),
        _disclaimer(),
    ]
    return "\n\n".join(s for s in sections if s) + "\n"


def _title(result: AnalysisResult) -> str:
    return (
        f"# Aesop Threat Model Report\n\n"
        f"**System:** {result.system_name}  \n"
        f"**Type:** {result.system_type}"
    )


def _system_summary(result: AnalysisResult) -> str:
    lines = ["## Architecture Summary\n"]
    for key, val in architecture_summary(result).items():
        lines.append(f"- **{key}:** {val}")
    return "\n".join(lines)


def _severity_summary(result: AnalysisResult) -> str:
    s = result.severity_summary
    return (
        "## Severity Summary\n\n"
        f"| Severity | Count |\n"
        f"|----------|-------|\n"
        f"| 🔴 Critical | {s.critical} |\n"
        f"| 🟠 High | {s.high} |\n"
        f"| 🟡 Medium | {s.medium} |\n"
        f"| 🟢 Low | {s.low} |\n"
        f"| **Total** | **{s.total}** |"
    )


def _findings_table(result: AnalysisResult) -> str:
    if not result.findings:
        return ""
    findings = sort_findings_by_severity(result.findings)
    lines = [
        "## Findings Overview\n",
        "| ID | Severity | Title | Category |",
        "|----|----------|-------|----------|",
    ]
    for f in findings:
        lines.append(
            f"| {f.id} | {severity_badge(f.severity)} | {f.title} | {f.category.value} |"
        )
    return "\n".join(lines)


def _detailed_findings(result: AnalysisResult) -> str:
    if not result.findings:
        return ""
    findings = sort_findings_by_severity(result.findings)
    parts = ["## Detailed Findings\n"]
    for f in findings:
        parts.append(_render_finding(f))
    return "\n\n".join(parts)


def _render_finding(f: Finding) -> str:
    lines = [
        f"### {severity_badge(f.severity)} {f.title}\n",
        f"**ID:** {f.id} | **Rule:** {f.rule_id} | **Confidence:** {f.confidence.value}\n",
        f"{f.summary}\n",
        f"{f.description}\n",
    ]

    if f.affected_components:
        lines.append(f"**Affected components:** {', '.join(f.affected_components)}\n")

    if f.evidence:
        lines.append("**Evidence:**\n")
        for e in f.evidence:
            lines.append(f"- {e}")
        lines.append("")

    if f.attack_path:
        lines.append(f"**Attack path:** {f.attack_path}\n")

    if f.atlas_techniques:
        lines.append("**ATLAS techniques:**\n")
        for t in f.atlas_techniques:
            lines.append(f"- `{t.technique_id}` — {t.technique_name}")
        lines.append("")

    if f.mitigations:
        lines.append("**Mitigations:**\n")
        for m in f.mitigations:
            lines.append(f"- {m}")
        lines.append("")

    return "\n".join(lines)


def _atlas_section(result: AnalysisResult) -> str:
    if not result.atlas_techniques_used:
        return ""
    lines = [
        "## MITRE ATLAS Mapping\n",
        "| Technique ID | Technique | Tactic |",
        "|-------------|-----------|--------|",
    ]
    for t in result.atlas_techniques_used:
        lines.append(f"| `{t.technique_id}` | {t.technique_name} | {t.tactic} |")
    return "\n".join(lines)


def _mitigations_summary(result: AnalysisResult) -> str:
    seen: set[str] = set()
    mitigations: list[str] = []
    for f in sort_findings_by_severity(result.findings):
        for m in f.mitigations:
            if m not in seen:
                seen.add(m)
                mitigations.append(m)

    if not mitigations:
        return ""

    lines = ["## Recommended Mitigations\n"]
    for i, m in enumerate(mitigations, 1):
        lines.append(f"{i}. {m}")
    return "\n".join(lines)


def _diagram_section(result: AnalysisResult) -> str:
    if not result.diagram_mermaid:
        return ""
    return (
        "## Architecture Diagram\n\n"
        "```mermaid\n"
        f"{result.diagram_mermaid}\n"
        "```"
    )


def _disclaimer() -> str:
    return (
        "---\n\n"
        "*This report was generated by [Aesop](https://github.com/muhammedcan/aesop), "
        "a deterministic threat modeling CLI for AI systems. Findings assist human "
        "review and do not replace formal security assessment.*"
    )
